name: Test

on:
  pull_request:
    branches: [main]

jobs:
  test:
    name: "ðŸ”¬ Test Saltman Action"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Saltman Action
        uses: adriangohjw/saltman@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

